#cloud-config
write_files:
  # Create file to be used when enabling ip forwarding
  - path: /etc/sysctl.d/98-ip-forward.conf
    content: |
      net.ipv4.ip_forward = 1
runcmd:
 - touch /root/userdata.`date +%s`.start  
 - echo 'OCIBase NAT Instance.' | sudo tee /etc/motd
 - systemctl stop postfix.service
 - systemctl disable postfix.service
  # Run firewall commands to enable masquerading and port forwarding
  # Enable ip forwarding by setting sysctl kernel parameter
 - firewall-offline-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -o ens3 -j MASQUERADE
 - firewall-offline-cmd --direct --add-rule ipv4 filter FORWARD 0 -i ens3 -j ACCEPT
 - /bin/systemctl restart firewalld
 - sysctl -p /etc/sysctl.d/98-ip-forward.conf
 - yum update -y 
 - touch /root/userdata.`date +%s`.finish